//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2Book.Windows.Legacy.Client.TaskServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int OrdinalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((this.OrdinalField.Equals(value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskServiceReference.TeamTaskServiceSoap")]
    public interface TeamTaskServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStatusesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatuses", ReplyAction="*")]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse GetStatuses(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse> GetStatusesAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest request);
        
        // CODEGEN: Generating message contract since element name GetStatusByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatusById", ReplyAction="*")]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse GetStatusById(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatusById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse> GetStatusByIdAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatuses", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequestBody Body;
        
        public GetStatusesRequest() {
        }
        
        public GetStatusesRequest(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStatusesRequestBody {
        
        public GetStatusesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponseBody Body;
        
        public GetStatusesResponse() {
        }
        
        public GetStatusesResponse(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status[] GetStatusesResult;
        
        public GetStatusesResponseBody() {
        }
        
        public GetStatusesResponseBody(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status[] GetStatusesResult) {
            this.GetStatusesResult = GetStatusesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusById", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequestBody Body;
        
        public GetStatusByIdRequest() {
        }
        
        public GetStatusByIdRequest(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int statusId;
        
        public GetStatusByIdRequestBody() {
        }
        
        public GetStatusByIdRequestBody(int statusId) {
            this.statusId = statusId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponseBody Body;
        
        public GetStatusByIdResponse() {
        }
        
        public GetStatusByIdResponse(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status GetStatusByIdResult;
        
        public GetStatusByIdResponseBody() {
        }
        
        public GetStatusByIdResponseBody(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status GetStatusByIdResult) {
            this.GetStatusByIdResult = GetStatusByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeamTaskServiceSoapChannel : WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeamTaskServiceSoapClient : System.ServiceModel.ClientBase<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap>, WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap {
        
        public TeamTaskServiceSoapClient() {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamTaskServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetStatuses(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest request) {
            return base.Channel.GetStatuses(request);
        }
        
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status[] GetStatuses() {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequestBody();
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse retVal = ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetStatuses(inValue);
            return retVal.Body.GetStatusesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse> WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetStatusesAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest request) {
            return base.Channel.GetStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesResponse> GetStatusesAsync() {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusesRequestBody();
            return ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetStatusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetStatusById(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest request) {
            return base.Channel.GetStatusById(request);
        }
        
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Status GetStatusById(int statusId) {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequestBody();
            inValue.Body.statusId = statusId;
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse retVal = ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetStatusById(inValue);
            return retVal.Body.GetStatusByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse> WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetStatusByIdAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest request) {
            return base.Channel.GetStatusByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdResponse> GetStatusByIdAsync(int statusId) {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetStatusByIdRequestBody();
            inValue.Body.statusId = statusId;
            return ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetStatusByIdAsync(inValue);
        }
    }
}
