//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2Book.Windows.Legacy.Client.TaskServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Link[] LinksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Link[] Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rel {
            get {
                return this.RelField;
            }
            set {
                if ((object.ReferenceEquals(this.RelField, value) != true)) {
                    this.RelField = value;
                    this.RaisePropertyChanged("Rel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Href {
            get {
                return this.HrefField;
            }
            set {
                if ((object.ReferenceEquals(this.HrefField, value) != true)) {
                    this.HrefField = value;
                    this.RaisePropertyChanged("Href");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskServiceReference.TeamTaskServiceSoap")]
    public interface TeamTaskServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse GetCategories(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse> GetCategoriesAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoryByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategoryById", ReplyAction="*")]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse GetCategoryById(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategoryById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse> GetCategoryByIdAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest() {
        }
        
        public GetCategoriesRequest(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody {
        
        public GetCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse() {
        }
        
        public GetCategoriesResponse(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category[] GetCategoriesResult;
        
        public GetCategoriesResponseBody() {
        }
        
        public GetCategoriesResponseBody(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category[] GetCategoriesResult) {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryById", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequestBody Body;
        
        public GetCategoryByIdRequest() {
        }
        
        public GetCategoryByIdRequest(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int categoryId;
        
        public GetCategoryByIdRequestBody() {
        }
        
        public GetCategoryByIdRequestBody(int categoryId) {
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponseBody Body;
        
        public GetCategoryByIdResponse() {
        }
        
        public GetCategoryByIdResponse(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category GetCategoryByIdResult;
        
        public GetCategoryByIdResponseBody() {
        }
        
        public GetCategoryByIdResponseBody(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category GetCategoryByIdResult) {
            this.GetCategoryByIdResult = GetCategoryByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeamTaskServiceSoapChannel : WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeamTaskServiceSoapClient : System.ServiceModel.ClientBase<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap>, WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap {
        
        public TeamTaskServiceSoapClient() {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamTaskServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamTaskServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetCategories(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest request) {
            return base.Channel.GetCategories(request);
        }
        
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category[] GetCategories() {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequestBody();
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse retVal = ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse> WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetCategoriesAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest request) {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesResponse> GetCategoriesAsync() {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoriesRequestBody();
            return ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetCategoryById(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest request) {
            return base.Channel.GetCategoryById(request);
        }
        
        public WebApi2Book.Windows.Legacy.Client.TaskServiceReference.Category GetCategoryById(int categoryId) {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequestBody();
            inValue.Body.categoryId = categoryId;
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse retVal = ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetCategoryById(inValue);
            return retVal.Body.GetCategoryByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse> WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap.GetCategoryByIdAsync(WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest request) {
            return base.Channel.GetCategoryByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdResponse> GetCategoryByIdAsync(int categoryId) {
            WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest inValue = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequest();
            inValue.Body = new WebApi2Book.Windows.Legacy.Client.TaskServiceReference.GetCategoryByIdRequestBody();
            inValue.Body.categoryId = categoryId;
            return ((WebApi2Book.Windows.Legacy.Client.TaskServiceReference.TeamTaskServiceSoap)(this)).GetCategoryByIdAsync(inValue);
        }
    }
}
